# Generated by Django 5.1.15 on 2026-09-29 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название письма"),
                ),
                (
                    "incoming_number",
                    models.CharField(max_length=100, verbose_name="№ входящего письма"),
                ),
                (
                    "saved_date",
                    models.CharField(max_length=20, verbose_name="Дата сохранения"),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Имя файла, под которым письмо сохранено на компьютере пользователя",
                        max_length=255,
                        verbose_name="Имя файла у пользователя",
                    ),
                ),
                (
                    "archive_filename",
                    models.CharField(
                        help_text="Имя файла в ARCHIVE_DIR на сервере (для повторного скачивания)",
                        max_length=64,
                        verbose_name="Служебное имя архивной копии",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
