# Generated by Django 5.1.15 on 2026-09-30 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название письма"),
                ),
                (
                    "incoming_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="№ входящего письма"
                    ),
                ),
                (
                    "processed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата обработки письма"
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата сохранения",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=1000, verbose_name="Путь к письму"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто сохранил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скан письма",
                "verbose_name_plural": "Сканы писем",
                "ordering": ["-saved_at", "-id"],
            },
        ),
    ]
